// +build !windows
package ascii

var (
	Tick               = "✔"
	Cross              = "✖"
	Star               = "★"
	Square             = "▇"
	SquareSmall        = "◻"
	SquareSmallFilled  = "◼"
	Circle             = "◯"
	CircleFilled       = "◉"
	CircleDotted       = "◌"
	CircleDouble       = "◎"
	CircleCircle       = "ⓞ"
	CircleCross        = "ⓧ"
	CirclePipe         = "Ⓘ"
	CircleQuestionMark = "?⃝"
	Bullet             = "●"
	Dot                = "․"
	Line               = "─"
	Ellipsis           = "…"
	Pointer            = "❯"
	PointerSmall       = "›"
	Info               = "ℹ"
	Warning            = "⚠"
	Hamburger          = "☰"
	Smiley             = "㋡"
	Mustache           = "෴"
	Heart              = "♥"
	ArrowUp            = "↑"
	ArrowDown          = "↓"
	ArrowLeft          = "←"
	ArrowRight         = "→"
	RadioOn            = "◉"
	RadioOff           = "◯"
	CheckboxOn         = "☒"
	CheckboxOff        = "☐"
	CheckboxCircleOn   = "ⓧ"
	CheckboxCircleOff  = "Ⓘ"
	QuestionMarkPrefix = "?⃝"
)
